---
title: "table"
format: pdf
editor: visual
---

```{r, echo=FALSE, include=FALSE}
library(tidyverse)
library(here)
library(kableExtra)
library(table1)
library(flextable)
library(dplyr)
library(purrr)
library(readr)
library(here)
library(countrycode)
library(gtsummary)
library(tableone)
library(ggplot2)
```


# Assignment 1 - Table 1 for armed conflict paper

```{r}
data <- read.csv("data/finaldata.csv")

baseline <- data %>%
  dplyr::filter(year == 2000)
baseline$armconf1f <- factor(baseline$armconf1, levels = c(0,1), 
                             labels = c("No armed conflict in 2000",
                                        "Armed conflict in 2000"))
baseline$droughtf <- factor(baseline$drought, levels = c(0,1), 
                            labels = c("No", "Yes"))
baseline$earthquakef <- factor(baseline$earthquake, levels = c(0,1), 
                               labels = c("No", "Yes"))
baseline$OECDf <- factor(baseline$OECD, levels = c(0,1), 
                         labels = c("No", "Yes"))

label(baseline$gdp1000)       <- "GDP per capita"
label(baseline$OECD)          <- "OECD member"
label(baseline$popdens)       <- "Population density"
label(baseline$urban)         <- "Urban residence"
label(baseline$agedep)        <- "Age dependency ratio"
label(baseline$male_edu)      <- "Male education"
label(baseline$temp)          <- "Mean annual temperature"
label(baseline$rainfall1000)  <- "Mean annual rain fall"
label(baseline$earthquakef)   <- "Earthquake"
label(baseline$earthquake)    <- "Earthquake"
label(baseline$droughtf)      <- "Drought"
label(baseline$drought)       <- "Drought"
label(baseline$armconf1f)     <- "Armed conflict"
label(baseline$totdeath)      <- "Total number of deaths"
label(baseline$matmor)        <- "Maternal mortality"
label(baseline$infmor)        <- "Infant mortality"
label(baseline$neomor)        <- "Neonatal mortality"
label(baseline$un5mor)        <- "Under 5 mortality"
label(baseline$armconf1f)     <- "Armed conflict"

units(baseline$gdp1000)       <- "USD"
units(baseline$popdens)       <- 
  "% of population living in a density of > 1,000 people/km^2"


table1(~ gdp1000 + OECDf + popdens + urban + agedep + male_edu + 
         temp + rainfall1000 + earthquakef + droughtf| armconf1f, 
       data = baseline,
       render.continuous = c(.="Median [Min, Max]"),
       overall=c(left="Total"), 
       caption = "Table 1: Descriptive Statistics of Socioeconomic Indicators 
  by Armed Conflict Status in 2000") 
```

\newpage 

# Assignment 2 - Descriptive figure

```{r}
finaldata <- read.csv("data/finaldata.csv", header = TRUE)

increased_maternal_mortality <- finaldata |>
  dplyr::select(country_name, ISO, year, matmor) |>
  dplyr::filter(year < 2018) |>
  group_by(ISO) |>
  mutate(diffmatmor = matmor - matmor[1L]) |>
  arrange(ISO, desc(year)) |>
  mutate(incmatmor = ifelse(diffmatmor[1L] > 0 , 1, 0)) |>
  arrange(ISO, year) |>
  ungroup() |>
  dplyr::filter(incmatmor == 1)
  length(unique(increased_maternal_mortality$ISO))

fig1 <- increased_maternal_mortality |>
  ggplot(aes(x = year, y = matmor, group = ISO)) +
  geom_line(aes(color = country_name), alpha = 1, linewidth = 1) +
  xlim(c(2000,2017)) +
  scale_y_continuous(trans='log10') + 
  labs(y = "Maternal mortality (log 10 scale)", x = "Year", 
       color = "Country", 
       title = "Trend in maternal mortality for countries that had an 
       increase from 2000 to 2017") + 
  theme_bw(base_size = 12)

fig1
```
